# Generated by Django 4.0.3 on 2022-03-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
