# Generated by Django 4.0.3 on 2022-03-06 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_customuser_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_created',
        ),
    ]
